Try fix command

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,7 +30,9 @@ jobs:
         cmake -D Vulkan_INCLUDE_DIR="${{env.VULKAN_SDK}}/include" \
           -D Vulkan_LIBRARY="${{env.VULKAN_SDK}}/lib/libvulkan.so" \
           -D CMAKE_INSTALL_PREFIX="${{env.InstallPath}}" .
-    - run: make -j 2
+    - run: make -j 2 >2 >(tee build.log >&2)
+    - name: Report
+      run: curl -s https://report.ci/annotate.py | python - --tool gcc --input build.log
     - run: make install
     - name: Publish artifact
       uses: actions/upload-artifact@v1
@@ -95,6 +97,6 @@ jobs:
         export PATH="$VULKAN_SDK:$VULKAN_SDK/bin:$PATH"
         cmake -D CMAKE_INSTALL_PREFIX="$GITHUB_WORKSPACE/../vsg-$GITHUB_SHA" .
     - name: Make
-      run: make -j 2 > (tee build.log >&2) 2>&1 || echo "Failed but ok"
+      run: make -j 2 >2 >(tee build.log >&2) || echo "Failed but ok"
     - name: Report
       run: curl -s https://report.ci/annotate.py | python - --tool gcc --input build.log
